# Python package


pool:
  name: Offshore Agent
#  demands:
#   Agent.OS -equals Windows
#  vmImage: ubuntu-16.04

trigger:
- master
- develop
- features/*
- hotfix/*
- release/*

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8.2'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python 3.8.2'

#- task: PowerShell@2
#  inputs:
#   targetType: 'inline'
#    script: |
#       py  pip install pipenv
#      pipenv shell
#      pipenv install selenium --dev
#      pipenv install pytest --dev
#      pipenv install openpyxl

- task: PipAuthenticate@1

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: |
#      pip install pipenv
#      pipenv shell
#      pipenv install selenium --dev
#      pipenv install pytest --dev
#      pipenv install openpyxl
#      pipenv install pytest-azurepipelines
#      pipenv install pytest-cov
#      pipenv run python -m pytest -v
#      echo 'Hello world'

#- bash: |
#   cd
#   pip install pipenv
#   pipenv shell
#   pipenv install selenium --dev
#   pipenv install pytest --dev
#   pipenv install openpyxl

#  displayName: 'Installations an Environment Setup'

- task: CmdLine@2
  inputs:
    script: |
       cd
       cd
       pip install pipenv
       pipenv shell
       pipenv install selenium --dev
       pipenv install pytest --dev
       pipenv install openpyxl
       pipenv install pytest-azurepipelines
       pipenv install pytest-xdist
       pipenv install pytest-cov
       pipenv run python -m pytest -v -n auto --cov=locators --cov=pages --cov=testingdata --cov=tests --cov-report xml
       
      
# displayName: 'Installations an Environment Setup'




#- script: |
#    pip install pipenv
#    pipenv shell
#    pipenv install selenium --dev
#    pipenv install pytest --dev
#    pipenv install openpyxl    
#  displayName: 'azure plugin install'

#- bash: |   
#   pipenv run python -m pytest -v -m Add_Certification --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

#  displayName: 'Run Test'
